services:
  app:
    build: ./docker/php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - postgres

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: jugador12
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
